### ISSUE TITLE
demo崩溃,随意点了几下

### ISSUE THREAD

**Issue by DogTwoChen** [ReverseScale/RSAutoWebView#1]
<img width="1399" alt="2018-08-14 9 46 12" src="https://user-images.githubusercontent.com/18676761/44067209-e6284ae4-9fa6-11e8-98ee-cfe6562f6596.png">
<img width="348" alt="2018-08-14 9 47 30" src="https://user-images.githubusercontent.com/18676761/44067247-29308518-9fa7-11e8-911f-d64b4860856d.png">
多点几下就崩溃,iPhone X  iOS11.4

**Comment by ReverseScale** [comment]
腾讯的 VAS·Sonic 有更新了，我当初就是体验一下，后期没跟 VAS·Sonic 的版本进度，VAS·Sonic 需要的后端支持，如果对速度要求不高，建议做常规缓存吧

**Comment by ReverseScale** [comment]
VAS·Sonic：https://github.com/Tencent/VasSonic
后期我跟进一下哈
